controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

recherche:
    path: /recherche
    controller: App\Controller\SearchController::index